[package]
name = "xycloans-pool"
description = "xycLoans pool contract. A secure and blazingly efficient implementation of DeFi primitive flash loans."
homepage = "https://xycloans.xycloo.com/"
repository = "https://github.com/xycloo/xycloans"
authors = ["Tommaso De Ponti <tommaso@xycloo.com>"]
readme = "README.md"
version = "1.0.0"
edition = "2021"

[lib]
name = "xycloans_pool"
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = ["moderc3156"]
moderc3156 = []
mercury = ["dep:retroshade-sdk"]

[dependencies]
soroban-sdk = { workspace = true }
fixed-point-math = { workspace = true }
retroshade-sdk = { version = "0.1.0", optional = true }

[dev_dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
fixed-point-math = { workspace = true }
